server { 
    # Defines a new server block to handle web requests
    
    listen 80; 
    # Tells Nginx to listen for incoming HTTP traffic on the default port 80

    location / { 
        # Defines the configuration for requests matching the root path ("/")

        proxy_set_header X-Real-IP $remote_addr; 
        # Forwards the actual IP address of the client to the backend (Node.js)

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        # Keeps track of every proxy the request passed through, adding the client's IP to the list

        proxy_set_header Host $http_host; 
        # Passes the original 'Host' header requested by the client to the backend server

        proxy_set_header X-NginX-Proxy true; 
        # A custom header telling the backend that this request came through an Nginx proxy

        proxy_pass http://node-app:4000; 
        # Forwards (proxies) the incoming traffic to the 'node-app' container running on port 4000

        proxy_redirect off; 
        # Prevents Nginx from modifying 'Location' or 'Refresh' headers sent by the backend server
    }
}